return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  cmd = {
    "MasonToolsInstall",
    "MasonToolsInstallSync",
    "MasonToolsUpdate",
    "MasonToolsUpdateSync",
    "MasonToolsClean",
  },
  dependencies = {
    "mason-org/mason.nvim",
  },
  opts = {
    ensure_installed = {
      "copilot-language-server",
      "clangd",
      "zls",
      "beautysh",
      "bash-language-server",
      "copilot-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "graphql-language-service-cli",
      "lua-language-server",
      "nil",
      "prettierd",
      "prisma-language-server",
      -- "python-lsp-server",
      "rust-analyzer",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "terraform-ls",
      "typescript-language-server",
      "typos-lsp",
      "yaml-language-server",
      "yamlfmt",
    },
  },
}
